tap "aws/tap"
tap "caddyserver/caddy"
tap "go-delve/delve"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "sqlite"
brew "babel"
brew "bandwhich"
brew "bash-completion"
brew "caddy", restart_service: true
brew "delve"
brew "diff-so-fancy"
brew "direnv"
brew "fzf"
brew "git"
brew "git-extras", link: false
brew "git-standup"
brew "go"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "mkcert"
brew "mtr"
brew "nginx", restart_service: true
brew "nmap"
brew "noti"
brew "pandoc"
brew "postgresql", restart_service: true
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "supervisor", restart_service: true, link: false
brew "telnet"
brew "tmux"
brew "vim"
cask "ngrok"
cask "vlc"
